### ISSUE TITLE
package to manage multi tenant

### ISSUE THREAD

**Issue by hacen-ai** [mjhea0/awesome-fastapi#100]
Hello,
Is there any package similaire to [django-tenants](https://github.com/django-tenants/django-tenants).

Thank you

**Comment by uolot** [comment]
This repository is about FastAPI, not Django, your package is irrelevant here.

**Comment by Kludex** [comment]
@hacen-ai is asking if there's a similar one in FastAPI, not to include that mentioned package here. :sweat_smile:

**Comment by uolot** [comment]
OMG, my apologies @hacen-ai, I misread your comment :see_no_evil:

**Comment by hacen-ai** [comment]
@uolot no worries
