### ISSUE TITLE
FastAPI Integration Category

### ISSUE THREAD

**Issue by ManiMozaffar** [mjhea0/awesome-fastapi#150]
Hey there,
does something like this considers as an awesome library?

https://github.com/ManiMozaffar/fastapi-integration

and which sub category would it be?
I have no idea how I can attach it, that's why i didn't open PR.
Maybe something as Core?

**Comment by mjhea0** [comment]
It could live under the "Boilerplate" section.

Unfortunately, I tend to only add projects that are at least a year old and are consistently being updated. Please open this PR again in May 2024.
