### ISSUE TITLE
Adding a new project

### ISSUE THREAD

**Issue by mdconaway** [mjhea0/awesome-fastapi#161]
Hi!

I am the developer / maintainer of this sort-of-batteries-included framework built on top of FastAPI.

https://github.com/mdconaway/fastapi-cruddy-framework

Would it be possible to get linked into your curated list?

Thanks!

**Comment by mjhea0** [comment]
I tend to only add projects that are at least a year old and are consistently being updated. Please open a PR in March 2024.
