### ISSUE TITLE
Python anywhere hosting

### ISSUE THREAD

**Issue by jeremylanglois** [mjhea0/awesome-fastapi#27]
Python anywhere is listed as a hosting solution but it's actually not working since it does not manage ASGI.

Please correct me if I'm wrong.

**Comment by Kludex** [comment]
Ok... Context is important. @jeremylanglois is talking about this section:
 
![image](https://user-images.githubusercontent.com/7353520/93687733-377fab00-fac0-11ea-8976-69ecc34e68c9.png)

Specifically about this service: https://www.pythonanywhere.com/ 

I don't have any opinions, just adding some context here.

**Comment by jeremylanglois** [comment]
Yes, and to be more specific, it's in their backlog (for at least a year) but not implemented:

[https://www.pythonanywhere.com/forums/topic/14918/](https://www.pythonanywhere.com/forums/topic/14918/)

**Comment by mjhea0** [comment]
Nice catch @jeremylanglois! Want to open a PR to remove it from the README?

**Comment by jeremylanglois** [comment]
I opened the PR: https://github.com/mjhea0/awesome-fastapi/pull/28

**Comment by mjhea0** [comment]
https://github.com/mjhea0/awesome-fastapi/pull/28
