### ISSUE TITLE
FastAPI Packages table

### ISSUE THREAD

**Issue by Kludex** [mjhea0/awesome-fastapi#40]
@mjhea0 Do you think [this](https://github.com/Kludex/fastapi-packages) can be useful here?

It's updated daily.

**Comment by mjhea0** [comment]
Yes, please add a PR. Thanks!

**Comment by Kludex** [comment]
But how do you see it? I mean, there's already information about some packages, do you want the table to duplicate the information about those or do you want me to remove that or...?

**Comment by mjhea0** [comment]
You could just add a link to your project.

**Comment by mjhea0** [comment]
Any more thoughts on this @Kludex?

**Comment by Kludex** [comment]
I'm going to add a link and that will do it.
