### ISSUE TITLE
FastAPI-security and FastAPI-auth are no longer maintained

### ISSUE THREAD

**Issue by SelfhostedPro** [mjhea0/awesome-fastapi#41]
Would be a good idea to remove them as no one is maintaining them.

**Comment by Kludex** [comment]
Maybe adding a note about it instead?

**Comment by mjhea0** [comment]
I like the idea of adding a note. It might help to bring attention to the projects so that they get new maintainers. Feel free to open a PR.

**Comment by Kludex** [comment]
Maintaining those notes is too hard. I propose the idea on the other issue to be used here. A list of FastAPI packages that updates daily is useful in this case.

**Comment by mjhea0** [comment]
@Kludex that doesn't really solve the unmaintained issue. You're implying that one can infer based on the last commit date whether or not a project is being maintained?

**Comment by mjhea0** [comment]
As far as I can tell, these packages still work just fine. They also solve issues that are not currently being solved by other packages. I'm hesitant to remove them. Any more thoughts on this @SelfhostedPro or @Kludex? Any thoughts @fkromer?

**Comment by SelfhostedPro** [comment]
I reached out to the devs of both of these packages and one confirmed it was no longer maintained. The other one never replied. Fastapi-jwt-auth fills the place of these nicely if you're looking for an alternative.

**Comment by SelfhostedPro** [comment]
Just based on the fact that they're security/auth plugins that aren't being maintained is the main reason I'm recommending removing them. If they weren't integral to the security of any application developed with them, I wouldn't have brought it up.

**Comment by Kludex** [comment]
> If they weren't integral to the security of any application developed with them, I wouldn't have brought it up.

I'm in favor of adding a note instead of removing them. Because the code source can still be used as inspiration for others. 

Something like `DANGER! SECURITY PACKAGE NO LONGER MAINTAINED!` or even an explanation as footnote with a `DANGER!` link to it.

**Comment by SelfhostedPro** [comment]
Something like:

:construction: unmaintained :construction: 

Next to the entry may be a good idea. Just add it when someone opens an issue about it or have them submit a PR.

Also, something like 

:rotating_light: developers wanted :rotating_light: 

Could be good for projects that are looking for help.

**Comment by fkromer** [comment]
@mjhea0 Sorry... FastAPI has not been my highest prio recently. In general... What about creating a FastAPI organization which receives, manages and distributes sponsoring revenue and takes care about maintenance of critical packages?

**Comment by mjhea0** [comment]
@fkromer that sounds like a nice idea, but I don't have time to do that right now.  @tiangolo - any thoughts on this?

**Comment by fkromer** [comment]
@mjhea0 Of course... the lack of time is the worst enemy of every developer 😄 It's not about implementing/maintaining everything yourself. I just meant to initiate the setup up of some "central point of contact". It's about making it more attractive for potential sponsors which usually depend on a working framework, not just the single "core" project. In my opinion for beeing competivite with other alternatives (ASP.NET, Spring Boot, etc.) this could be essential.
