### ISSUE TITLE
Section for "Built with FastAPI"

### ISSUE THREAD

**Issue by SelfhostedPro** [mjhea0/awesome-fastapi#59]
May be a good idea to add a section for FastAPI projects that are opensource so people can get inspiration or see how other projects accomplish things. I know I spent a while looking through projects to see how they did JWT or authentication in general with FastAPI. 

Happy to submit [my project](https://github.com/selfhostedpro/yacht) :wink:

**Comment by Kludex** [comment]
I don't see why not. Awesome project presentation, just beautiful! :star_struck:

**Comment by SelfhostedPro** [comment]
Ah, I must have missed that. I'll see about doing a PR when I've got some time.
