### ISSUE TITLE
demystifying-authentication-with-fastapi-and-a-frontend broken

### ISSUE THREAD

**Issue by jmcdonald24** [mjhea0/awesome-fastapi#86]
This link is not working: demystifying-authentication-with-fastapi-and-a-frontend

**Comment by Kludex** [comment]
:sleeping: 

Their website is down right now: https://kernelpanic.io/demystifying-authentication-with-fastapi-and-a-frontend/

**Comment by mjhea0** [comment]
Down for me as well.

We could use the archive.org version: https://web.archive.org/web/20210403011419/https://kernelpanic.io/demystifying-authentication-with-fastapi-and-a-frontend/

?

**Comment by Kludex** [comment]
I guess. :+1:
