### ISSUE TITLE
Which section should I put this resource?

### ISSUE THREAD

**Issue by cassiobotaro** [mjhea0/awesome-fastapi#9]
https://pypi.org/project/faastapi/ - Easily create OpenFaas functions built on top of FastAPI Python framework

**Comment by mjhea0** [comment]
I guess it could be added to the [Open Source Projects](https://github.com/mjhea0/awesome-fastapi#open-source-projects) section. I didn't originally include that project since it doesn't have a GitHub or GitLab or docs homepage. Is the project still alive?

**Comment by cassiobotaro** [comment]
I saw that is not open source. Closing this issue.
